// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWwunybp5Obb-ThceIqX4aBMStHuzwak',
    appId: '1:1041280523312:web:1e4d96407ebff255bae1f5',
    messagingSenderId: '1041280523312',
    projectId: 'study-anything-aed2b',
    authDomain: 'study-anything-aed2b.firebaseapp.com',
    storageBucket: 'study-anything-aed2b.firebasestorage.app',
    measurementId: 'G-90BJJJCWDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeGPopMk_P9b3wQhdBk6TEOCx6FL1mGNE',
    appId: '1:1041280523312:android:37184e610167c952bae1f5',
    messagingSenderId: '1041280523312',
    projectId: 'study-anything-aed2b',
    storageBucket: 'study-anything-aed2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqWybFeG_5MaRTXTmILOPLBleFLcElqO4',
    appId: '1:1041280523312:ios:9f2003a8acda4f0cbae1f5',
    messagingSenderId: '1041280523312',
    projectId: 'study-anything-aed2b',
    storageBucket: 'study-anything-aed2b.firebasestorage.app',
    iosBundleId: 'com.example.studyAnything',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqWybFeG_5MaRTXTmILOPLBleFLcElqO4',
    appId: '1:1041280523312:ios:9f2003a8acda4f0cbae1f5',
    messagingSenderId: '1041280523312',
    projectId: 'study-anything-aed2b',
    storageBucket: 'study-anything-aed2b.firebasestorage.app',
    iosBundleId: 'com.example.studyAnything',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwWwunybp5Obb-ThceIqX4aBMStHuzwak',
    appId: '1:1041280523312:web:b72c22dfc4394019bae1f5',
    messagingSenderId: '1041280523312',
    projectId: 'study-anything-aed2b',
    authDomain: 'study-anything-aed2b.firebaseapp.com',
    storageBucket: 'study-anything-aed2b.firebasestorage.app',
    measurementId: 'G-KYG30KYKD9',
  );
}
